var e=void 0,f=!0,h=null,n=!1;function r(){this.version=e}r.prototype={d:function(){var a=navigator.userAgent;this.version=parseFloat(a.slice(a.indexOf("Xcode/")+6,a.length));u("xcode4.css","xcode4");5<=this.version&&u("xcode5.css","xcode5")}};
function u(a,b){var c=document.getElementsByTagName("head")[0],d;d=c.querySelector("link[rel=stylesheet]").href;d=d.substring(0,d.lastIndexOf("/")+1);var g=document.createElement("link");g.setAttribute("rel","stylesheet");g.setAttribute("type","text/css");g.setAttribute("href",d+a);g.setAttribute("id",b);c.appendChild(g)}window.addEventListener("DOMContentLoaded",function(){-1<navigator.userAgent.indexOf("Xcode/")?(xcode=new r,xcode.d()):xcode=e});function v(a){var b={},c,d=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||function(a){window.setTimeout(a,50)}}(),g=window.cancelAnimationFrame||window.cancelRequestAnimationFrame||window.webkitCancelAnimationFrame||window.webkitCancelRequestAnimationFrame||window.mozCancelAnimationFrame||window.mozCancelRequestAnimationFrame||window.clearTimeout,m,k=h,p=a.parentNode.querySelector(".svg-play-button"),l=0,q=0,z=0,s=0,t=n;return{d:function(c){b=
c||{p:50,H:800,L:5};k=a.contentDocument.querySelectorAll("svg > g");q=k.length;z=Math.round(b.H/b.p);l=q-1},start:function(){m=Date.now();var a=this;(function K(){c=d(K);a.loop()})();t=f;p.classList.add("faded")},loop:function(){var a=Date.now(),c=a-m;c>b.p&&(1<=l&&(k[l].style.display="block",l!==q-1&&(k[l+1].style.display="none")),this.next(),m=a-c%b.p)},next:function(){l===-1*z?s===b.L-1?this.stop():(k[1].style.display="none",l=q-1,k[l].style.display="block",s++):l--},stop:function(){g(c);for(var a=
1;a<k.length;a++)k[a].style.display="none";l=q-1;k[l].style.display="block";s=0;p.classList.remove("faded");t=n},w:function(){return t}}};function w(){this.id="mini_toc";this.I=n;this.a=this.element=e;this.s=0;this.n=n}
w.prototype={d:function(){x(this);return this},open:function(){var a=0;Array.prototype.forEach.call(this.element.children,function(b){a+=b.clientHeight});this.element.style.height=a+15+"px";this.a.classList.add("active")},close:function(){this.element.style.height="25px";this.a.classList.remove("active")},J:function(){mini_toc.element.style.height="25px";mini_toc.element.classList.remove("open");mini_toc.a.classList.remove("active")},toggle:function(a){a.preventDefault();-1<(" "+mini_toc.element.className+
" ").indexOf("open")?(mini_toc.close(),mini_toc.element.classList.remove("open")):(mini_toc.element.classList.add("open"),mini_toc.open())},q:function(a){a.preventDefault();var b=document.getElementsByTagName("article")[0];mini_toc.close();mini_toc.element.classList.remove("open");var c={};history.state!==h&&(c=history.state);c.o=b.innerHTML;c.scrollY=window.scrollY;c.scrollX=window.scrollX;history.replaceState(c,b.innerHTML,window.location.href);a=a.target.getAttribute("href");var d=document.getElementsByName(a.substring(1,
a.length))[0].nextSibling.nextSibling;d.scrollIntoView(f);d.focus();c.scrollY=window.scrollY;c.scrollX=window.scrollX;history.pushState(c,b.innerHTML,a)},g:function(a){var b=this;Array.prototype.forEach.call(a.getElementsByTagName("a"),function(a){a.addEventListener("click",b.q)})}};
function y(a){iphone||document.addEventListener("scroll",function(){if(!(-1<(" "+a.element.className+" ").indexOf("open"))){var b=window.pageYOffset;0>=b?(a.element.classList.remove("slide-out"),a.n=n):!a.n&&b>a.s?(a.element.classList.add("slide-out"),a.n=f):a.n&&b<a.s&&(a.element.classList.remove("slide-out"),a.n=n);a.s=b}})}
function x(a){var b=document.getElementById(a.id);b&&(a.I=f,a.a=document.getElementById("big_button"),a.element=b,a.g(b),document.getElementById("mini_toc_button").addEventListener("click",a.toggle),a.a.addEventListener("click",mini_toc.J),y(a))}window.addEventListener("load",function(){mini_toc=new w;mini_toc.d()});function Navigator(){this.className="part-name";this.b=this.B=h}
Navigator.prototype={d:function(){this.B=document.getElementsByClassName(this.className);"roadmap"!==document.body.getAttribute("id")&&this.g();return this},D:function(){var a=e;historian.c&&(a=historian.c.getElementsByTagName("ul")[0]);a===e&&nav_parts.b!==e&&(a=nav_parts.b);a!==e&&("0px"!==a.style.height&&"UL"===a.nodeName)&&(a.style.height="100%")},open:function(a){a&&"UL"===a.nodeName&&(a.parentElement.classList.add("nav-part-active"),this.b=a.parentElement,a.parentElement.addEventListener("transitionend",
this.D,f),a.parentElement.classList.add("open-part"),"roadmap"!==document.body.id&&A(a))},close:function(){this.b&&"roadmap"!==document.body.id&&(this.b.classList.remove("open-part"),this.b.style.height="0px");this.b&&this.b.parentElement!==h&&this.b.parentElement.classList.remove("nav-part-active")},q:function(a){a=a.target.getElementsByTagName("ul")[0];if(a!==e){nav_parts.close();nav_parts.open(a);nav_parts.b=a;a=a.children[0].children[0];if(a.href!==window.location.href){var b=document.querySelector('a[data-id="'+
a.getAttribute("data-id")+'"]');B(b,a);C(a)}ipad!==e&&ipad.h()}},g:function(){var a=this;Array.prototype.forEach.call(a.B,function(b){b.addEventListener("click",a.q)})}};
function D(){var a=document.getElementsByTagName("article")[0].getElementsByTagName("a")[0].getAttribute("name");if(a=document.querySelector('a[data-id="'+a+'"]')){if(a.href){var b=window.location.pathname;a.href=b.substring(b.lastIndexOf("/")+1,b.length)+a.hash}if((b=a.parentElement)&&"LI"===b.nodeName)b=b.parentElement,nav_parts.open(b),nav_parts.b=b,a.classList.add("nav-chapter-active"),a.parentElement.classList.add("nav-current-chapter"),historian.e=a,historian.c=b}}
function A(a){var b=0;Array.prototype.forEach.call(a.children,function(a){b+=a.clientHeight});a.style.height=b+"px"}window.addEventListener("load",function(){nav_parts=new Navigator;nav_parts.d()});function History(){this.u=h;this.t=f;this.v=this.c=this.e=h}
History.prototype={d:function(){var a=document.getElementsByClassName("book-parts");0<a.length&&E(this,a[0].getElementsByTagName("a"));a=document.getElementById("next_previous");a!==h&&(a=a.querySelectorAll('a:not([rel="external"])'),E(this,a));this.u=document.getElementsByTagName("article")[0].innerHTML;this.v=document.getElementsByTagName("title")[0].innerHTML},z:function(){var a=h,b=document.querySelectorAll(".svg-container");Array.prototype.forEach.call(b,function(b){b=b.querySelector(".svg-animation");
var d=new v(b);d.d();b.contentDocument.querySelector("svg").addEventListener("click",function(){a&&(d!==a&&a.w())&&a.stop();d.w()||(d.start(),a=d)})});ipad!==e&&ipad.l();iphone!==e&&iphone.l();Array.prototype.forEach.call(document.getElementsByTagName("video"),function(a){new F(a)})},K:function(a){if(!a.metaKey&&!a.ctrlKey)if(a.preventDefault(),a.target.href===window.location.href)a=document.getElementsByTagName("h2")[0],a.scrollIntoView(n),a.focus();else{var b=a.target,c=document.querySelector('a[data-id="'+
a.target.getAttribute("data-id")+'"]');B(c,b);C(a.target)}},Q:function(){},O:function(){},P:function(){},N:function(){}};function G(a,b,c){b!==h?a.innerHTML=b.getElementsByTagName("title")[0].innerHTML:c!==e&&(a.innerHTML=c)}
function H(a,b){var c=document.getElementsByTagName("article")[0];c.innerHTML=b;var d=document.getElementById("next_previous").querySelectorAll('a:not([rel="external"])');E(a,d);var g=[];Array.prototype.forEach.call(c.getElementsByClassName("x-name"),function(a){g.push(a.firstChild)});E(a,g);mini_toc!==e&&x(mini_toc);window.setTimeout(historian.z,2E3)}
function C(a){var b=historian,c=new XMLHttpRequest;c.addEventListener("progress",b.Q,n);c.addEventListener("load",b.O,n);c.addEventListener("error",b.P,n);c.addEventListener("abort",b.N,n);c.onreadystatechange=function(){if(4===c.readyState){var d=c.responseText,g=document.createElement("div");g.innerHTML=d;H(b,g.getElementsByTagName("article")[0].innerHTML);var d=document.getElementsByTagName("article")[0],m=document.getElementsByTagName("title")[0];G(m,g,h);g={};g.o=d.innerHTML;g.G=historian.e.getAttribute("data-id");
g.R=m.innerHTML;g.scrollY=window.scrollY;g.scrollX=window.scrollX;var m=document.querySelector('a[data-id="'+a.getAttribute("data-id")+'"]'),k=h,p=h;if(a.getAttribute("data-id")===h||a.getAttribute("data-id")===e)historian.c=e,nav_parts.close();m!==h&&(k=m.parentNode.parentNode.parentNode,p=m.parentNode.parentNode);k===h||-1<k.className.split(" ").indexOf("nav-part-active")||(nav_parts.close(),nav_parts.open(p),nav_parts.b=p,historian.c=document.getElementsByClassName("nav-part-active")[0]);g.c=historian.c!==
e?historian.c.getAttribute("data-id"):h;historian.t=n;history.pushState(g,a.innerHTML,a.href);if(d=d.getElementsByTagName("h2")[0])d.scrollIntoView(n),d.focus();"undefined"!==typeof PageTracker&&(d={},document.referrer&&(d.referrer=document.referrer),d.identifier=document.getElementById("identifier").content,PageTracker.logEvent("ajaxPageLoad",d))}};c.open("GET",a.href);c.send()}function E(a,b){Array.prototype.forEach.call(b,function(b){b.addEventListener("click",a.K)})}
function B(a,b){if(historian.e){historian.e.classList.remove("nav-chapter-active");historian.e.parentElement.classList.remove("nav-current-chapter");var c=b.parentElement.classList.contains("next-link"),d=b.parentElement.classList.contains("previous-link");(c||d)&&historian.e.parentElement.classList.add("nav-visited-chapter")}a!==h&&(a.classList.add("nav-chapter-active"),a.parentElement.classList.add("nav-current-chapter"),historian.e=a,historian.c=document.getElementsByClassName("nav-part-active")[0],
historian.c.addEventListener("transitionend",nav_parts.D,f),A(historian.c.getElementsByTagName("ul")[0]))}
window.onpopstate=function(a){var b=a.state;a=document.getElementsByTagName("title")[0];if(b)b.o!==h&&H(historian,b.o),G(a,h,b.title),historian.e&&(historian.e.classList.remove("nav-chapter-active"),historian.e.parentElement.classList.remove("nav-current-chapter")),a=document.querySelector('a[data-id="'+b.G+'"]'),a.classList.add("nav-chapter-active"),a.parentElement.classList.add("nav-current-chapter"),historian.e=a,b.c!==h?part_chapters=document.querySelector('li[data-id="'+b.c+'"]').children[0]:
(nav_parts.close(),part_chapters=e),part_chapters!==e&&(nav_parts.close(),nav_parts.open(part_chapters),nav_parts.b=part_chapters),b.scrollY!==e&&b.scrollY!==h&&window.setTimeout(function(){window.scrollTo(b.scrollX,b.scrollY)},100);else{if(historian.t){historian.z();var c=[];Array.prototype.forEach.call(document.getElementsByTagName("article")[0].getElementsByClassName("x-name"),function(a){c.push(a.firstChild)});E(historian,c)}else H(historian,historian.u),G(a,h,historian.v);nav_parts.close();(a=
document.getElementsByClassName("nav-part-active")[0])&&a.classList.remove("nav-part-active");if(a=document.getElementsByClassName("nav-chapter-active")[0])a.classList.remove("nav-chapter-active"),a.parentElement.classList.remove("nav-current-chapter");D()}};window.addEventListener("load",function(){historian=new History;historian.d();D()});function I(){this.search=this.a=this.i=this.f=this.j=e}
I.prototype={d:function(){this.i=document.getElementsByClassName("book-parts")[0];this.f=document.getElementById("shortstack");this.j=document.getElementsByTagName("article")[0];this.a=document.getElementById("big_button");this.search=document.getElementById("search");this.g();this.l();window.addEventListener("deviceorientation",this.M,f)},l:function(){var a=document.querySelectorAll("figure > img"),b=document.getElementsByClassName("inline-graphic");Array.prototype.forEach.call(a,function(a){a.removeAttribute("height");
a.removeAttribute("width")});Array.prototype.forEach.call(b,function(a){a.removeAttribute("height");a.removeAttribute("width")})},g:function(){ipad.f.addEventListener("click",ipad.m);ipad.j.addEventListener("click",ipad.h);ipad.a.addEventListener("click",ipad.h);ipad.search.addEventListener("click",ipad.r)},r:function(a){"FORM"===a.target.nodeName&&(document.getElementById("ssi_SearchField").classList.toggle("enabled"),ipad.search.classList.toggle("enabled"))},C:function(){ipad.f.removeEventListener("click",
ipad.m);ipad.j.removeEventListener("click",ipad.h)},h:function(){ipad.i.classList.remove("open");ipad.a.classList.remove("active");ipad.f.classList.remove("enabled")},m:function(){ipad.i.classList.toggle("open");ipad.a.classList.add("active");ipad.f.classList.toggle("enabled")},M:function(){90===Math.abs(window.orientation)?(ipad.i.classList.remove("open"),ipad.C()):ipad.g();nav_parts.b.style.height="100%"}};
document.addEventListener("DOMContentLoaded",function(){/(iPad).*AppleWebKit/i.test(navigator.userAgent)?(ipad=new I,ipad.d()):ipad=e});function J(){this.search=this.a=this.i=this.f=this.j=e}
J.prototype={d:function(){this.i=document.getElementsByClassName("book-parts")[0];this.f=document.getElementById("shortstack");this.j=document.getElementsByTagName("article")[0];this.a=document.getElementById("big_button");this.search=document.getElementById("search");this.g();this.l()},l:function(){var a=document.querySelectorAll("figure > img");Array.prototype.forEach.call(a,function(a){a.removeAttribute("height");a.removeAttribute("width")});Array.prototype.forEach.call(document.getElementsByClassName("inline-graphic"),
function(a){a.removeAttribute("height");a.removeAttribute("width")})},g:function(){iphone.f.addEventListener("click",iphone.m);iphone.j.addEventListener("click",iphone.h);iphone.a.addEventListener("click",iphone.h);iphone.search.addEventListener("click",iphone.r)},r:function(a){"FORM"===a.target.nodeName&&(document.getElementById("ssi_SearchField").classList.toggle("enabled"),iphone.search.classList.toggle("enabled"))},C:function(){iphone.f.removeEventListener("click",iphone.m);iphone.j.removeEventListener("click",
iphone.h)},h:function(){iphone.i.classList.remove("open");iphone.a.classList.remove("active");iphone.f.classList.remove("enabled");document.querySelector(".chapter").classList.remove("frozen")},m:function(){iphone.i.classList.toggle("open");iphone.a.classList.add("active");iphone.f.classList.toggle("enabled");document.querySelector(".chapter").classList.toggle("frozen")}};
document.addEventListener("DOMContentLoaded",function(){/(iP(hone|opd)).*AppleWebKit/i.test(navigator.userAgent)?(iphone=new J,iphone.d()):iphone=e});function F(a){var b=this,c=a.parentNode;a.addEventListener("click",function(a){L(b,a)});a.addEventListener("touchend",function(a){L(b,a)});a.addEventListener("play",function(){b.play()});a.addEventListener("pause",function(){b.pause()});a.addEventListener("ended",function(){b.pause();b.k.element.currentTime=0});a.addEventListener("keypress",function(a){32===a.keyCode&&(a.preventDefault(),L(b,a))});b.F=24;b.k={element:a};b.A=c.querySelector(".playButtonOverlay");return b.k.element}
F.prototype={play:function(){var a=this.k.element;this.A.classList.add("hide");a.play();a.focus()},pause:function(){var a=this.A;this.k.element.pause();a.classList.remove("hide")}};function L(a,b){b&&b.offsetY>a.k.element.videoHeight-a.F||(a.k.element.paused?a.play():a.pause())};

//# sourceMappingURL=./devpubs.js.map