function k(a){return document.querySelector(a)}function n(a){return document.querySelectorAll(a)}HTMLElement.prototype.c=HTMLElement.prototype.querySelector;HTMLElement.prototype.l=HTMLElement.prototype.querySelectorAll;HTMLElement.prototype.index=function(){return Array.prototype.indexOf.call(this.parentNode.childNodes,this)};
window.requestAnimationFrame||(window.requestAnimationFrame=window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||function(a){setTimeout(a,1E3/60)});window.cancelAnimationFrame||(window.cancelAnimationFrame=window.webkitCancelAnimationFrame||window.mozCancelAnimationFrame||window.oCancelAnimationFrame||function(a){clearTimeout(a)});
window.matchesSelector||(HTMLElement.prototype.matchesSelector=HTMLElement.prototype.webkitMatchesSelector||HTMLElement.prototype.mozMatchesSelector||HTMLElement.prototype.Da);window.na=function(){var a=document.body.style;return"webkitTransition"in a?"webkitTransitionEnd":"mozTransition"in a?"transitionend":"oTransition"in a?"otransitionend":"transitionend"};function p(a,b){for(var c=a.parentNode;c!==document;){if(c.matchesSelector(b))return c;c=c.parentNode}return null}
NodeList.prototype.forEach=Array.prototype.forEach;Array.prototype.contains=function(a){for(var b=this.length;b--;)if(this[b]===a)return!0;return!1};Array.prototype.G=function(){return 0<this.length?this[this.length-1]:this[0]};NodeList.prototype.G=Array.prototype.G;Array.prototype.remove=function(a){Array.isArray(a)||(a=[a]);for(var b=a.length-1;0<=b;b--)for(var c=this.length-1;0<=c;c--)this[c]===a[b]&&this.splice(c,1);return this};
function q(a,b){var c=this;a.split(" ").forEach(function(a){c.addEventListener(a,b)})}window.d=q;document.d=q;HTMLElement.prototype.d=q;function u(){this.search=this.m=this.n=this.u=void 0}
u.prototype={e:function(){this.m=document.getElementsByClassName("book-parts")[0];this.n=document.getElementById("shortstack");this.u=document.getElementsByTagName("article")[0];this.search=document.getElementById("search");this.p();window.addEventListener("orientationchange",this.wa,!0)},L:function(){var a=document.querySelectorAll("figure > img"),b=document.getElementsByClassName("inline-graphic");Array.prototype.forEach.call(a,function(a){a.removeAttribute("height");a.removeAttribute("width")});
Array.prototype.forEach.call(b,function(a){a.removeAttribute("height");a.removeAttribute("width")})},p:function(){ipad.n.addEventListener("click",ipad.V);ipad.u.addEventListener("click",ipad.v);ipad.search.addEventListener("click",ipad.T)},T:function(a){"FORM"===a.target.nodeName&&(document.getElementById("ssi_SearchField").classList.toggle("enabled"),ipad.search.classList.toggle("enabled"))},v:function(){ipad.m.classList.remove("open");ipad.n.classList.remove("enabled")},V:function(){ipad.m.classList.toggle("open");
ipad.n.classList.toggle("enabled")},wa:function(){90===Math.abs(window.orientation)&&ipad.m.classList.contains("open")&&ipad.m.classList.remove("open")}};document.addEventListener("DOMContentLoaded",function(){/(iPad).*AppleWebKit/i.test(navigator.userAgent)?(ipad=new u,ipad.e()):ipad=void 0});function v(){this.search=this.w=this.m=this.n=this.u=void 0}
v.prototype={e:function(){this.m=document.getElementsByClassName("book-parts")[0];this.n=document.getElementById("shortstack");this.u=document.getElementsByTagName("article")[0];this.w=document.getElementById("big_button");this.search=document.getElementById("search");this.p();this.L()},L:function(){var a=document.querySelectorAll("figure > img");Array.prototype.forEach.call(a,function(a){a.removeAttribute("height");a.removeAttribute("width")});Array.prototype.forEach.call(document.getElementsByClassName("inline-graphic"),
function(a){a.removeAttribute("height");a.removeAttribute("width")})},p:function(){iphone.n.addEventListener("click",iphone.V);iphone.u.addEventListener("click",iphone.v);iphone.w.addEventListener("click",iphone.v);iphone.search.addEventListener("click",iphone.T)},T:function(a){"FORM"===a.target.nodeName&&(document.getElementById("ssi_SearchField").classList.toggle("enabled"),iphone.search.classList.toggle("enabled"))},v:function(){iphone.m.classList.remove("open");iphone.w.classList.remove("active");
iphone.n.classList.remove("enabled");document.querySelector(".chapter").classList.remove("frozen")},V:function(){iphone.m.classList.toggle("open");iphone.w.classList.add("active");iphone.n.classList.toggle("enabled");document.querySelector(".chapter").classList.toggle("frozen")}};document.addEventListener("DOMContentLoaded",function(){/(iP(hone|opd)).*AppleWebKit/i.test(navigator.userAgent)?(iphone=new v,iphone.e()):iphone=void 0});function w(){}w.prototype={e:function(){document.getElementById("legacyOuterWrapper")&&this.show();return this},show:function(){document.getElementById("legacyOuterWrapper").classList.add("show");document.getElementById("LegacyNoticeCloseBox").addEventListener("click",this.close)},close:function(){document.getElementById("legacyOuterWrapper").classList.remove("show");document.getElementById("LegacyNoticeCloseBox").removeEventListener("click",this.close)}};window.addEventListener("load",function(){(new w).e()});function History(){this.aa=this.$=null;this.Z=!0;this.ba=this.i=this.k=null}
History.prototype={e:function(){var a=document.getElementsByClassName("book-parts");0<a.length&&x(this,a[0].getElementsByTagName("a"));a=document.getElementById("next_previous");null!==a&&(a=a.querySelectorAll('a:not([rel="external"])'),x(this,a));this.$=document.getElementsByTagName("article")[0].innerHTML;null!==document.getElementsByTagName("menu")&&(this.aa=document.getElementsByTagName("menu")[0].innerHTML);this.ba=document.getElementsByTagName("title")[0].innerHTML},ea:function(){var a=null,
b=document.querySelectorAll(".svg-container");Array.prototype.forEach.call(b,function(b){b=b.querySelector(".svg-animation");var e=new aa(b);e.e();b.contentDocument.querySelector("svg").addEventListener("click",function(){a&&e!==a&&a.da()&&a.stop();e.da()||(e.start(),a=e)})});void 0!==iphone&&iphone.L();Array.prototype.forEach.call(document.getElementsByTagName("video"),function(a){new y(a)})},ra:function(a){if(!a.metaKey&&!a.ctrlKey){a.preventDefault();var b=window.location.origin+window.location.pathname,
c=a.target.origin+a.target.pathname;a.target.href===window.location.href?(b=a.target.hash,""===b&&(b="#"+a.target.getAttribute("data-id")),b=document.getElementsByName(b.substring(1,b.length)),b[0].scrollIntoView()):c===b?(""!==a.target.hash?b=document.getElementsByName(a.target.hash.substring(1,a.target.hash.length)):(b="#"+a.target.getAttribute("data-id"),b=document.getElementsByName(b.substring(1,b.length))),b[0].scrollIntoView()):(b="#"+a.target.getAttribute("data-id"),z(historian,a.target,b));
var b=a.target,c=document.getElementById("navigator"),e=c.querySelector('a[data-id="'+a.target.getAttribute("data-id")+'"]');null===e&&(e=a.target.getAttribute("data-id").slice(0,a.target.getAttribute("data-id").lastIndexOf("-")),e=c.querySelector('a[data-id^="'+e+'"]'),null===e&&(a=a.target.getAttribute("href"),e=c.querySelector('a[href^="'+a.substring(0,a.lastIndexOf("#"))+'"]')));A(e,b)}},Aa:function(){},ya:function(){},za:function(){},xa:function(){}};
function B(a,b,c){null!==b?a.innerHTML=b.getElementsByTagName("title")[0].innerHTML:void 0!==c&&(a.innerHTML=c)}function C(a,b){var c=document.getElementsByTagName("article")[0];c.innerHTML=b;var e=document.getElementById("next_previous").querySelectorAll('a:not([rel="external"])');x(a,e);c=c.querySelectorAll('a[href]:not([href^="../"]):not([href^="http"]):not([class="playground"])');x(a,c);void 0!==mini_toc&&D(mini_toc);window.setTimeout(historian.ea,2E3)}
function E(a){document.getElementById("bashful").innerHTML=a;void 0!==mini_toc&&D(mini_toc);null!==document.getElementById("jump_to")&&(jumper=new F("#jump_to"))}
function z(a,b,c){var e=new XMLHttpRequest;e.addEventListener("progress",a.Aa,!1);e.addEventListener("load",a.ya,!1);e.addEventListener("error",a.za,!1);e.addEventListener("abort",a.xa,!1);e.onreadystatechange=function(){if(4===e.readyState){var g=e.responseText,f=document.createElement("div");f.innerHTML=g;E(f.getElementsByTagName("menu")[0].innerHTML);C(a,f.getElementsByTagName("article")[0].innerHTML);var g=document.getElementsByTagName("article")[0],m=document.getElementsByTagName("menu")[0],
r=document.getElementsByTagName("title")[0];B(r,f,null);f={};f.J=g.innerHTML;f.U=m.innerHTML;f.X=historian.k.getAttribute("data-id");f.Ba=r.innerHTML;f.scrollY=window.scrollY;f.scrollX=window.scrollX;g=document.getElementsByClassName("partless");g=0===g.length?null:g[0];r=m=null;if(null===b.getAttribute("data-id")||void 0===b.getAttribute("data-id"))historian.i=void 0,nav_parts.close();else{var l=document.getElementById("navigator"),h=l.querySelector('a[data-id="'+b.getAttribute("data-id")+'"]');
null!==g&&(h=l.querySelector('li[data-id="'+b.getAttribute("data-id")+'"]'));null===h&&(h=b.getAttribute("href"),h=l.querySelector('a[href^="'+h.substring(0,h.lastIndexOf("#"))+'"]'))}null!==h&&(m=h.parentNode.parentNode.parentNode,r=h.parentNode.parentNode,null!==g&&(m=h,r=h.getElementsByClassName("nav-chapters")[0]));null===m||-1<m.className.split(" ").indexOf("nav-part-active")||(nav_parts.close(),nav_parts.open(r),nav_parts.j=r,historian.i=document.getElementsByClassName("nav-part-active")[0]);
f.i=void 0!==historian.i?historian.i.getAttribute("data-id"):null;historian.Z=!1;history.pushState(f,b.innerHTML,b.href);h=b.hash.substring(1,b.hash.length);h=document.getElementsByName(h);f=document.getElementsByTagName("h2")[0];f.scrollIntoView(!1);f.focus();void 0!==c&&(h=c.substring(1,c.length),h=document.getElementsByName(h));0<h.length&&h[0].scrollIntoView();"undefined"!==typeof PageTracker&&(h={},document.referrer&&(h.referrer=document.referrer),h.identifier=document.getElementById("identifier").content,
PageTracker.logEvent("ajaxPageLoad",h))}};e.open("GET",b.href);e.send()}function x(a,b){Array.prototype.forEach.call(b,function(b){b.addEventListener("click",a.ra)})}
function A(a,b){if(historian.k){historian.k.classList.remove("nav-chapter-active");historian.k.parentElement.classList.remove("nav-current-chapter");var c=b.parentElement.classList.contains("next-link"),e=b.parentElement.classList.contains("previous-link");(c||e)&&historian.k.parentElement.classList.add("nav-visited-chapter")}null!==a&&(a.classList.add("nav-chapter-active"),a.parentElement.classList.add("nav-current-chapter"),historian.k=a,historian.i=document.getElementsByClassName("nav-part-active")[0],
G(),H(historian.i.getElementsByTagName("ul")[0]))}
window.onpopstate=function(a){if("reference"!==document.body.id){var b=a.state;a=document.getElementsByTagName("title")[0];if(b)null!==b.J&&C(historian,b.J),null!==b.U&&E(b.U),B(a,null,b.title),historian.k&&(historian.k.classList.remove("nav-chapter-active"),historian.k.parentElement.classList.remove("nav-current-chapter")),a=document.querySelector('a[data-id="'+b.X+'"]'),a.classList.add("nav-chapter-active"),a.parentElement.classList.add("nav-current-chapter"),historian.k=a,null!==b.i?part_chapters=
document.querySelector('li[data-id="'+b.i+'"]').children[0]:(nav_parts.close(),part_chapters=void 0),void 0!==part_chapters&&(nav_parts.close(),nav_parts.open(part_chapters),nav_parts.j=part_chapters),void 0!==b.scrollY&&null!==b.scrollY&&window.setTimeout(function(){window.scrollTo(b.scrollX,b.scrollY)},100);else{if(historian.Z){historian.ea();a=document.getElementsByTagName("article")[0];var c=[];Array.prototype.forEach.call(a.getElementsByClassName("x-name"),function(a){c.push(a.firstChild)});
x(historian,c);a=a.querySelectorAll('a[href]:not([href^="../"]):not([href^="http"]):not([class="playground"])');x(historian,a)}else C(historian,historian.$),E(historian.aa),B(a,null,historian.ba);nav_parts.close();(a=document.getElementsByClassName("nav-part-active")[0])&&a.classList.remove("nav-part-active");if(a=document.getElementsByClassName("nav-chapter-active")[0])a.classList.remove("nav-chapter-active"),a.parentElement.classList.remove("nav-current-chapter");I()}}};
window.addEventListener("load",function(){"reference"!==document.body.id&&"collection"!==document.body.id&&(historian=new History,historian.e())});function J(){this.id="bashful";this.element=void 0}
J.prototype={e:function(){D(this);return this},R:function(a){a.preventDefault();var b=document.getElementsByTagName("article")[0],c={};null!==history.state&&(c=history.state);c.J=b.innerHTML;c.scrollY=window.scrollY;c.scrollX=window.scrollX;c.U=document.getElementById("bashful").innerHTML;c.X=historian.k.getAttribute("data-id");c.i=document.getElementsByClassName("nav-part-active")[0].getAttribute("data-id");history.replaceState(c,b.innerHTML,window.location.href);a=a.target.getAttribute("href");
var e=document.getElementsByName(a.substring(1,a.length))[0];window.scrollTo(0,e.offsetTop+45);e.focus();c.scrollY=window.scrollY;c.scrollX=window.scrollX;history.pushState(c,b.innerHTML,a);jumper.close()},p:function(a){var b=this;Array.prototype.forEach.call(a.getElementsByTagName("a"),function(a){a.addEventListener("click",b.R)})}};function D(a){var b=document.getElementById(a.id);b&&(a.element=b,a.p(b))}
window.addEventListener("load",function(){"reference"!==document.body.id&&"collection"!==document.body.id&&(mini_toc=new J,mini_toc.e())});function Navigator(){this.className="part-name";this.j=this.ga=null}
Navigator.prototype={e:function(){this.ga=document.getElementsByClassName(this.className);"guidance"!==document.body.getAttribute("id")&&this.p();return this},open:function(a){a&&"UL"===a.nodeName&&(a.parentElement.classList.add("nav-part-active"),this.j=a.parentElement,G(),a.parentElement.classList.add("open-part"),"roadmap"!==document.body.id&&H(a))},close:function(){this.j&&"roadmap"!==document.body.id&&(this.j.parentElement.classList.remove("open-part"),this.j.style.height="0px");this.j&&null!==
this.j.parentElement&&this.j.parentElement.classList.remove("nav-part-active")},R:function(a){var b=a.target,c=void 0;if("LI"===b.nodeName)"A"===b.firstChild.nodeName&&(c=b.firstChild);else if("A"===b.nodeName&&!1===b.parentElement.classList.contains("part-name"))return;if(void 0!==c&&!0===b.classList.contains("nav-part-active"))A(c,c);else{var e=b.getElementsByTagName("ul")[0];void 0!==e&&(nav_parts.close(),nav_parts.open(e),nav_parts.j=e,(e=e.children[0].children[0])&&e.hasAttribute("href")&&e.href!==
window.location.href&&(void 0!==c?A(c,c):A(e,a.target),z(historian,e,b.getAttribute("data-id"))),void 0!==ipad&&ipad.v())}},p:function(){var a=this;Array.prototype.forEach.call(a.ga,function(b){b.addEventListener("click",a.R)})}};
function I(){var a=nav_parts,b=document.getElementsByTagName("article")[0].getElementsByTagName("a")[1].getAttribute("name");if(b=document.querySelector('a[data-id="'+b+'"]')){if(b.href){var c=window.location.pathname;b.href=-1!=c.indexOf(".html")?c.substring(c.lastIndexOf("/")+1,c.length)+b.hash:"index.html"+b.hash}(c=b.parentElement)&&"LI"===c.nodeName&&(c=c.parentElement,a.open(c),a.j=c,b.classList.add("nav-chapter-active"),b.parentElement.classList.add("nav-current-chapter"),historian.k=b,historian.i=
c)}}function H(a){var b=0;Array.prototype.forEach.call(a.children,function(a){b+=a.clientHeight});a.style.height=b+15+"px"}function G(){var a;historian.i&&(a=historian.i.getElementsByTagName("ul")[0]);void 0===a&&void 0!==nav_parts.j&&(a=nav_parts.j);void 0!==a&&"0px"!==a.style.height&&"UL"===a.nodeName&&(a.style.height="100%")}window.addEventListener("load",function(){"reference"!==document.body.id&&(nav_parts=new Navigator,nav_parts.e(),I())});function F(a){this.ha=a;this.b=k(a);this.f=!1;this.a={filter:this.b.c(".filter"),h:this.b.l(".item a"),matches:this.b.c("#filter_matches")};this.la=[];this.index=-1;this.matches=this.a.h.length;this.b.c(".JavaScript")&&document.body.classList.add("js");ba();this.a.h.forEach(function(a){this.la.push(a.textContent)}.bind(this));this.r()}
F.prototype={r:function(){K.prototype.r.call(this);null!==this.a.filter&&this.a.filter.d("focus",function(){this.index=-1;L(this);k("#bashful").classList.remove("slide-out");this.open()}.bind(this));this.b.c(".details").d("mousewheel",function(a){var b=a.wheelDeltaY;0<b&&0===this.scrollTop?a.preventDefault():0>b&&this.scrollTop===this.scrollHeight-this.clientHeight&&a.preventDefault()});document.d("keydown",function(a){if(this.f)switch(a.keyCode){case 27:""===this.a.filter.value&&this.close();break;
case 38:a.preventDefault();0<=this.index&&(this.index--,this.focus());break;case 40:a.preventDefault();this.index<this.matches-1&&(this.index++,this.focus());break;case 13:a.preventDefault(),this.b.c(".focused")&&(a=this.b.c(".focused").getAttribute("href"),ca(ref,a),this.close())}}.bind(this));null!==this.a.filter&&this.filter()},filter:function(){null!==this.a.filter&&this.a.filter.d("input",function(){var a=this.a.filter.value.trim().toLowerCase(),b,c=0;this.la.forEach(function(e){if(""===a)this.a.h[c].textContent=
e,this.a.h[c].classList.remove("hidden");else if(/^\+( )?/.test(a)){b=RegExp("^\\+( )?"+a.substring(1),"i");var g=this.a.h[c],f=b;f.test(e)?M(g,f,e):g.classList.add("hidden")}else/^-( )?/.test(a)?(b=RegExp("^-( )?"+a.substring(1),"i"),g=this.a.h[c],f=b,f.test(e)?M(g,f,e):g.classList.add("hidden")):0<=e.toLowerCase().indexOf(a)?(b=RegExp(a,"gi"),M(this.a.h[c],b,e)):this.a.h[c].classList.add("hidden");c++}.bind(this));da(this)}.bind(this))},open:function(){K.prototype.open.call(this);null!==this.a.filter&&
(this.a.filter.focus(),da(this))},close:function(){K.prototype.close.call(this);null!==this.a.filter&&this.a.filter.blur();L(this);this.index=-1;L(this)},toggle:function(){K.prototype.toggle.call(this)},focus:function(){L(this);if(0>this.index&&null!==this.a.filter)this.a.filter.focus();else if(this.index<this.matches){null!==this.a.filter&&this.a.filter.blur();var a=ea(),a=this.b.l(a+".item:not(.hidden) a:not(.hidden)")[this.index];a.classList.add("focused");a.scrollIntoViewIfNeeded()}}};
function L(a){a.b.c(".focused")&&a.b.c(".focused").classList.remove("focused")}function ea(){return document.body.classList.contains("js")?".JavaScript ":document.body.classList.contains("swift")?".Swift ":document.body.classList.contains("obj_c")||document.body.classList.contains("both")?".Objective-C ":""}
function da(a){if(null!==a.a.matches){var b=ea();a.matches=a.b.l(b+".item:not(.hidden) a:not(.hidden)").length;a.a.matches.textContent=null!==a.a.filter&&""===a.a.filter.value?"":a.matches+" match"+(1!==a.matches?"es":"")}}function M(a,b,c){a.classList.remove("hidden");a.innerHTML=c.replace(b,'<span class="highlighted">$&</span>')}
function ba(){n("#jump_to a").forEach(function(a){var b=k('[name="'+a.getAttribute("href").substring(1)+'"]');if(b&&"reference"===document.body.id&&(b=p(b,".task-group-term"))){var c=p(b,".symbol");a.setAttribute("data-availability",c.dataset.availability);b.classList.contains("deprecated")&&p(a,".item").classList.add("deprecated")}})};function K(a){this.ha=a;this.b=k(a);this.f=!1;this.r()}
K.prototype={r:function(){this.b.d("click",function(a){p(a.target,".details")||this.toggle()}.bind(this));document.d("click",function(a){this.f&&a.target!==this.b&&!p(a.target,this.ha)&&(a.preventDefault(),this.close())}.bind(this));this.b.d(window.na(),function(){this.f||(this.b.classList.remove("closing"),this.b.classList.add("closed"))}.bind(this))},open:function(){this.f||(this.b.classList.remove("closed"),this.b.classList.add("open"),this.f=!0)},close:function(){this.f&&(this.b.classList.remove("open"),
this.b.classList.add("closing"),this.f=!1)},toggle:function(){this.f?this.close():this.open()}};function fa(a,b){this.Q=b;this.data={};this.a={K:k(".chapter"),g:{language:k("#language"),deployment_target:k("#deployment_target"),deprecated:k("#deprecated"),auto_expand:k("#auto_expand")},h:n(".symbol"),ja:n(".task-group"),va:n(".task-group-section"),Ga:n(".nav-parts .tasks .nav-chapter"),pa:n('.chapter #reference_container > section[class="section"]')};this.C=!1;this.ma=null;this.S=0;this.I={W:-1<navigator.userAgent.indexOf("Xcode/"),sa:-1<navigator.userAgent.indexOf("iPad")}}
fa.prototype={r:function(){this.I.sa||(ga(this),ha(this),ia(),ja());ka(this);la(this)}};function ka(a){window.d("resize",function(){ma()}.bind(a))}function ia(){k("nav.book-parts .tasks").d("mousewheel",function(a){var b=a.wheelDeltaY;this.scrollHeight!==this.clientHeight&&(0<b&&0===this.scrollTop?a.preventDefault():0>b&&this.scrollTop===this.scrollHeight-this.clientHeight&&a.preventDefault())})}
function N(a,b){var c=k('[name="'+b.substring(1)+'"]');if(c&&"reference"===document.body.id){var e=p(c,".symbol"),g=k("a").title,f="";if(e)O(a,e,!1),P(a,e).f||R(a,e),c=c.parentNode.l("a[href]"),c[0].getClientRects()[0]?f=c[0].textContent+" - ":c[1].getClientRects()[0]&&(f=c[1].textContent+" - "),document.title=f+g;else if(e=p(c,".task-group"))O(a,e,!1),f=c.parentNode.c(".section-name").textContent,document.title=f+" - "+g}}
function oa(){var a=ref;k("a");var b=window.location.hash;b&&(window.localStorage&&"true"===localStorage.getItem("com.apple.devpubs.auto_expand")?setTimeout(function(){N(this,b)}.bind(a),500):N(a,b))}function pa(){var a=ref,b=k(".overview-bulk"),c=k(".overview-bulk-toggle");b&&c.d("click",function(){b.classList.remove("hidden");b.classList.remove("squashed");c.parentNode.removeChild(c);S(this,b.clientHeight)}.bind(a))}
function ja(){function a(){n(".active-task").forEach(function(a){a.classList.remove("active-task")})}var b=k(".tasks"),c=n(".tasks .nav-chapter a"),e=[];c.forEach(function(a){a=a.getAttribute("href").substring(1);a=k('a[name="'+a+'"]');e.push(a)});document.d("scroll",function(){var g=!1;0>=window.pageYOffset?(a(),b.scrollTop=0):window.pageYOffset>=document.height-window.innerHeight?0<c.length&&(a(),c[c.length-1].classList.add("active-task"),b.scrollTop=99999):e.forEach(function(b){if(!g){var c=b.getClientRects()[0].top;
25>=Math.abs(c)&&(a(),b=k('.tasks .nav-chapter a[href="#'+b.name+'"]'),b.classList.add("active-task"),0<window.pageYOffset&&window.pageYOffset<document.height-window.innerHeight&&b.scrollIntoViewIfNeeded(),g=!0)}})})}function ha(a){document.d("keypress",function(a){!a.metaKey||102!==a.keyCode&&103!==a.keyCode||this.C||qa(this)}.bind(a))}
function ga(a){document.d("keydown",function(a){if(!/(textarea|input)/i.test(document.activeElement.nodeName)&&!a.metaKey){if(68===a.keyCode)return this.a.g.deprecated.checked=!this.a.g.deprecated.checked,ra(this),!1;if(65===a.keyCode)return this.a.g.auto_expand.checked=!this.a.g.auto_expand.checked,sa(this),!1}}.bind(a))}
function qa(a){a.C=!0;var b=!1;k(".overview-bulk")&&k(".overview-bulk").classList.remove("hidden");n(".symbol .height-container.hidden").forEach(function(a){a.classList.remove("hidden")});ta(a);var c=setInterval(function(){var a=document.getSelection();if("Range"===a.type){b=!0;var g=a.baseNode.parentNode,f=p(g,".squashed"),g=p(g,".height-container");f?k(".overview-bulk-toggle").click():g&&(f=p(g,".item"),P(this,f).f||R(this,f));this.ma!==a.baseNode&&(setTimeout(function(){window.scrollTo(0,window.pageYOffset+
1)},700),this.ma=a.baseNode)}else b&&this.C&&(clearInterval(c),this.C=!1,n(".symbol:not(.on) .height-container").forEach(function(a){a.classList.add("hidden")}))}.bind(a),16)}function ta(a){var b=a.a.h.G(),b=ua(a)-T(a,b);S(a,b);k(".last-one").style.paddingBottom=b+"px"}function ua(a){var b=0;a.a.h.forEach(function(a){a=P(this,a).q+T(this,a);a>b&&(b=a)}.bind(a));return b}
function la(a){n('#language input[type="radio"]').forEach(function(a){a.d("change",function(){va(this,a)}.bind(this))}.bind(a));k("#ssi_SearchField").d("focus",function(){this.P.close()}.bind(a));a.a.g.deployment_target.d("change",function(){wa(this)}.bind(a));a.a.g.deprecated.d("change",function(){ra(this)}.bind(a));a.a.g.auto_expand.d("change",function(){sa(this)}.bind(a))}
function va(a,b){var c=b.id;k("#language .selected")&&k("#language .selected").classList.remove("selected");p(b,"#language").c('label[for="'+b.id+'"]').classList.add("selected");["swift","objective_c","javascript","both"].forEach(function(a){document.body.classList.remove(a)});document.body.classList.add(c);a.a.h.forEach(function(a){var b=P(this,a);if(b.f){var f=b.q;xa(b);ya(this,a,b.q-f)}else b.N=!0;"objective_c"===c&&b.F||"swift"===c&&b.D?(U(this,a),V(b)):(!b.B||b.B&&!this.a.g.deprecated.checked)&&
(isNaN(b.o)||b.o<=this.a.g.deployment_target.value)&&b.show()}.bind(a));W(a);X(a);Y(a,b)}
function za(){var a=n(".instance-method .declaration .Swift .para, .class-method .declaration .Swift .para, .function .declaration .Swift .para");a.forEach(function(a){var c=a.textContent.trim().split(/, /);if(1!==c.length){var e=a.innerHTML.split(/, /),g=0;c.forEach(function(a){a=a.split(c[0]!==a||/^init/.test(c[0])?" ":"(")[0].length;a>g&&(g=a)});var f=0;c.forEach(function(a){e[f]=Array(g-(/:/.test(a)?a.split(c[0]!==a||/^init/.test(c[0])?" ":"(")[0].length:-10)+1).join("&nbsp;")+e[f];f++});a.innerHTML=
e.join(",<br />")}});a=n(".instance-method .declaration .Objective-C .para, .class-method .declaration .Objective-C .para");a.forEach(function(a){a.l(".parameter-name").forEach(function(a){a.innerHTML+="<br />"});for(var c=a.l(".nl"),e=0,e="",g=1;g<c.length;g++)e=a.textContent.trim().split(":")[0].length-c[g].textContent.length+2,0<e&&(e=Array(e).join("&nbsp;"),c[g].innerHTML=e+c[g].textContent);a=a.l(".n");for(g=0;g<a.length;g++)/,/.test(a[g].textContent)&&(e=Array(c[c.length-1].textContent.length+
10).join("&nbsp;"),a[g].innerHTML=a[g].innerHTML.replace(/,/g,",<br />"+e))})}function ca(a,b,c){c&&c.metaKey?(a=window.location,window.open(a.origin+a.pathname+b,"_blank")):(N(a,b),history.replaceState(null,null,b))}
function Aa(){var a=ref;n('.nav-parts .tasks a, .para .x-api, .para .x-class-method, .para a.x-instance-method, #jump_to a, .chapter .declaration a[href^="#"]').forEach(function(a){a.d("click",function(c){c.preventDefault();var e=a.getAttribute("href");ca(this,e,c);return!1}.bind(this))}.bind(a))}
function Y(a,b){var c,e;switch(b.type){case "radio":c="language";e=b.id;break;case "checkbox":c=b.id;e=b.checked;break;case "select-one":c=b.id,e=b.value}a.I.W||!window.localStorage?document.cookie="com.apple.devpubs."+c+"="+e+";expires="+(new Date("April 2, 2999")).toGMTString()+";path=/":localStorage.setItem("com.apple.devpubs."+c,e)}
function Ba(){function a(a,b){if(a&&b&&"false"!==b){switch(a.type){case void 0:a=a.c("#"+b);a.checked=!0;break;case "checkbox":a.checked=!0;break;case "select-one":a.value=b}var c=document.createEvent("UIEvents");c.initEvent("change",!1,!1);a.dispatchEvent(c,a)}}var b=ref;if(b.I.W||!window.localStorage)document.cookie.split(";").forEach(function(b){if(b){var c=b.split("=")[0].trim().replace("com.apple.devpubs.","");c&&(c=k("#"+c),a(c,b.split("=")[1].trim()))}});else for(var c in b.a.g){var e="deployment_target"===
c?"_"+b.Q:"",g=k("#"+c+e),e=localStorage.getItem("com.apple.devpubs."+c+e);a(g,e)}}function sa(a){var b;a.a.g.auto_expand.checked?(b=n(".symbol:not(.on):not(.hidden)"),Ca(a,b)):(b=n(".symbol.on"),Da(a,b));Y(a,a.a.g.auto_expand)}
function W(a){function b(a,b,g,f){if(0<b){var m=1===b?"":"s";a.textContent=b+" "+g+" symbol"+m+" hidden";a.title="To show "+(1===b?"this":"these")+" symbol"+m+", change your "+f+".";a.classList.remove("hidden")}else a.classList.add("hidden")}a.a.ja.forEach(function(a){var e=0,g=0,f=0,m=0;P(this,a).h.forEach(function(a){a=P(this,a);a.O&&(a.F&&document.body.classList.contains("objective_c")?g++:a.D&&document.body.classList.contains("swift")?e++:a.B&&this.a.g.deprecated.checked?f++:a.o>this.a.g.deployment_target.value&&
m++)}.bind(this));var r=a.c(".hiding-swift"),l=a.c(".hiding-obj-c"),h=a.c(".hiding-dep");a=a.c(".hiding-dt");r&&l&&h&&a&&(b(r,e,"Objective-C","language setting"),b(l,g,"Swift","language setting"),b(h,f,"deprecated","setting in the Options menu"),b(a,m,"newer","setting in the Options menu"))}.bind(a))}function X(a){var b=a.S,c=k("#reference_container").clientHeight;0<a.S&&S(a,c-b);a.S=c}
function ra(a){var b=!1;n(".deprecated").forEach(function(a){a.parentElement.classList.contains("constant")&&a.parentElement.parentElement.classList.contains("list-bullet")&&a.parentElement.parentElement.querySelector(".constant").forEach(function(a){null===a.querySelector(".deprecated")&&(b=!0)});var e=p(a,".symbol");e&&!1===b?(U(this,e),a=P(this,e),this.a.g.deprecated.checked?V(a):a.F&&document.body.classList.contains("objective_c")||a.D&&document.body.classList.contains("swift")||a.o>this.a.g.deployment_target.value||
a.show()):a.classList.toggle("hidden")}.bind(a));W(a);X(a);Y(a,a.a.g.deprecated)}
function wa(a){var b=parseFloat(a.a.g.deployment_target.value,10);a.P.a.h.forEach(function(a){var e=p(a,".item");e.classList.contains("deprecated")||(a=parseFloat(a.dataset.o,10),a>b?e.classList.add("hidden"):a<=b&&e.classList.remove("hidden"))});a.a.h.forEach(function(a){var e=P(this,a);if(!e.B)if(e.o>b)U(this,a),V(e);else{(document.body.classList.contains("objective_c")&&!e.F||document.body.classList.contains("swift")&&!e.D||document.body.classList.contains("both"))&&e.show();var g=a.c(".task-group-term .new");
e.o===b?g||(g=document.createElement("span"),g.className="new",g.innerHTML="(New in "+("mac"===this.Q?"OS X":"iOS")+" "+("mac"===this.Q?"v10.":"")+b+")",a.c(".task-group-term").appendChild(g)):g&&a.c(".task-group-term").removeChild(g)}}.bind(a));W(a);X(a);Y(a,a.a.g.deployment_target)}function T(a,b){var c=P(a,b),e=b.offsetTop,g=c.y,f=20;c.H&&(f=P(a,c.H).y);return e+g+f+P(a,c.ka).y}function O(a,b,c){b=T(a,b)-27;c?Ea(a.ia,b):window.scrollTo(0,b+1);a.P.close()}
function ya(a,b,c){var e=P(a,b).H,g=p(e,".task-group-section");[b,e,g].forEach(function(a){var b=c,e=a.index();a=a.parentNode.childNodes;for(var e=e+1,g=a.length;e<g;e++)if(1===a[e].nodeType){var h=a[e],s=0;void 0!==P(this,h)&&(s=P(this,h).y||0);var s=s+b,t=h.style;"webkitTransform"in t?h.style.webkitTransform="translateY("+s+"px)":"mozTransform"in t?h.style.Ca="translateY("+s+"px)":"oTransform"in t?h.style.Ea="translateY("+s+"px)":"transform"in t&&(h.style.transform="translateY("+s+"px)");void 0!==
P(this,h)&&(P(this,h).y=s)}}.bind(a));k(".last-one").classList.contains("fat")||(k(".last-one").classList.add("fat"),c+=750);S(a,c)}function R(a,b){var c=P(a,b),e=c.q;c.f&&(e*=-1);0<e&&(b.c(".height-container").classList.remove("hidden"),c.N&&(xa(c),e=c.q,c.N=!1));ya(a,b,e);c.toggle();b.classList.toggle("on")}function U(a,b){P(a,b).f&&R(a,b)}function Da(a,b){b.forEach(function(a){U(this,a)}.bind(a))}function Ca(a,b){b.forEach(function(a){P(this,a).f||R(this,a)}.bind(a))}
function S(a,b){var c=0;0!==b&&(b?c=parseInt(a.a.K.style.height,10)+b:(0<a.a.h.length&&n(".hiding-symbol-counts").G().classList.add("last-one"),c=a.a.K.clientHeight),a.a.K.style.height=c+"px")}function ma(){var a=k(".nav-parts .part-name.tasks"),b=window.innerHeight-70-32-(k(".nav-parts").clientHeight-a.clientHeight),b=Math.max(b,61);a.style.maxHeight=b+"px"}
function Fa(){var a=ref,b=0;a.a.h.forEach(function(a){var c=new Ga(a),f="s"+b++;c.e(f);this.data[f]=c;a.l(".task-group-term a[href]").forEach(function(b){b.d("click",function(f){if(!f.metaKey){f.preventDefault();if(!c.f){var l=a.getClientRects()[0].top;f=P(this,a).q;var h=window.innerHeight;l+f+30>h&&(l=T(this,a),Ea(this.ia,f+30<h-97?l-(h-f-30-70-10):l-27));history.replaceState(null,null,b.href)}R(this,a)}}.bind(this))}.bind(this))}.bind(a));b=0;a.a.ja.forEach(function(a){var c=new Ha(a),f="tg"+b++;
c.e(f);this.data[f]=c;a.c(".section-name").d("click",function(b){if(!b.metaKey){b.preventDefault();var f=!c.f;f&&O(this,a,!0);a.l(".symbol:not(.hidden)").forEach(function(a){var b=P(this,a).f;(f&&!b||!f&&b)&&R(this,a)}.bind(this));c.toggle()}}.bind(this))}.bind(a));var b=0,c=a.a.va;c.forEach(function(a){var c="c"+b++;a=new Z(a);a.e(c);this.data[c]=a}.bind(a));b=0;c=a.a.pa;c.forEach(function(a){if(0===b)b++;else{var c="c"+(b-1);b++;a=new Z(a);a.e(c);this.data[c]=a}}.bind(a));b=0;n(".hiding-symbol-counts").forEach(function(a){a=
new Z(a);var c="h"+b++;a.e(c);this.data[c]=a}.bind(a))}function P(a,b){return a.data[b.id]}document.d("DOMContentLoaded",function(){null!==document.getElementById("jump_to")&&(jumper=new F("#jump_to"));if(k("#reference")){var a=k("#book-title");a&&(a.getAttribute("content"),a=k("#ios_header .header-text a").textContent.split(" ")[0].toLowerCase(),ref=new fa(0,a),za(),ref.I.W||(ref.ia=new Ia,ref.P=jumper,ref.Fa=new K("#options"),ma(),Fa(),S(ref),Aa(),ref.r(),X(ref),Ba(),oa(),pa()))}});function Ia(){this.ta=/(iPad|iPhone|iPod).*AppleWebKit/i.test(navigator.userAgent);this.Y=null;this.A=this.s=0;this.ca=!1}Ia.prototype={};function Ea(a,b){var c=window.pageYOffset;a.s=c;a.A=b;a.ca=c<b;var e=Math.round((b-c)/(300/(1E3/60)));0!==e&&function f(){a.Y=window.requestAnimationFrame(f);a.s+=e;(a.ta?0:a.ca?a.s<a.A:a.s>a.A)?window.scrollTo(0,a.s):(window.scrollTo(0,a.A+1),window.cancelAnimationFrame(a.Y))}()};function Z(a){this.b=a;this.O=this.f=!1;this.y=0;return this}Z.prototype={e:function(a){this.b.setAttribute("id",a)},show:function(){this.b.classList.remove("hidden");this.O=!1},toggle:function(){this.f=!this.f}};function V(a){a.b.classList.add("hidden");a.O=!0};function Ga(a){this.b=a;this.q=a.c(".section").clientHeight+15;this.H=p(a,".task-group");this.ka=p(this.H,".task-group-section");this.B=!!this.b.c(".deprecated");this.F=this.b.classList.contains("swift-only");this.D=this.b.classList.contains("obj-c-only");this.o=parseFloat(a.dataset.availability,10);this.N=!1;a.c(".height-container").classList.add("hidden");a.d(window.na(),function(){this.classList.contains("on")||this.c(".height-container").classList.add("hidden");k(".last-one").classList.contains("fat")&&
(k(".last-one").classList.remove("fat"),S(ref,-750))});return this}Ga.prototype=new Z;function xa(a){a.q=a.b.c(".section").clientHeight+15};function Ha(a){this.b=a;this.h=a.l(".symbol");this.ka=p(a,".task-group-section");return this}Ha.prototype=new Z;function aa(a){var b={},c,e=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||function(a){window.setTimeout(a,50)}}(),g=window.cancelAnimationFrame||window.cancelRequestAnimationFrame||window.webkitCancelAnimationFrame||window.webkitCancelRequestAnimationFrame||window.mozCancelAnimationFrame||window.mozCancelRequestAnimationFrame||window.clearTimeout,f,m=null,r=a.parentNode.querySelector(".svg-play-button"),l=0,h=0,s=0,t=0,Q=!1;return{e:function(c){b=
c||{M:50,qa:800,ua:5};m=a.contentDocument.querySelectorAll("svg > g");h=m.length;s=Math.round(b.qa/b.M);l=h-1},start:function(){f=Date.now();var a=this;(function Ka(){c=e(Ka);a.loop()})();Q=!0;r.classList.add("faded")},loop:function(){var a=Date.now(),c=a-f;c>b.M&&(1<=l&&(m[l].style.display="block",l!==h-1&&(m[l+1].style.display="none")),this.next(),f=a-c%b.M)},next:function(){l===-1*s?t===b.ua-1?this.stop():(m[1].style.display="none",l=h-1,m[l].style.display="block",t++):l--},stop:function(){g(c);
for(var a=1;a<m.length;a++)m[a].style.display="none";l=h-1;m[l].style.display="block";t=0;r.classList.remove("faded");Q=!1},da:function(){return Q}}};function y(a){var b=this,c=a.parentNode;a.addEventListener("click",function(a){$(b,a)});a.addEventListener("touchend",function(a){$(b,a)});a.addEventListener("play",function(){b.play()});a.addEventListener("pause",function(){b.pause()});a.addEventListener("ended",function(){b.pause();b.t.element.currentTime=0});a.addEventListener("keypress",function(a){32===a.keyCode&&(a.preventDefault(),$(b,a))});b.oa=24;b.t={element:a};b.fa=c.querySelector(".playButtonOverlay");return b.t.element}
y.prototype={play:function(){var a=this.t.element;this.fa.classList.add("hide");a.play();a.focus()},pause:function(){var a=this.fa;this.t.element.pause();a.classList.remove("hide")}};function $(a,b){b&&b.offsetY>a.t.element.videoHeight-a.oa||(a.t.element.paused?a.play():a.pause())};function Ja(){this.version=void 0}Ja.prototype={e:function(){var a=navigator.userAgent;this.version=parseFloat(a.slice(a.indexOf("Xcode/")+6,a.length));if(5<=this.version){var a=document.getElementsByTagName("head")[0],b;b=a.querySelector("link[rel=stylesheet]").href;b=b.substring(0,b.lastIndexOf("/")+1);var c=document.createElement("link");c.setAttribute("rel","stylesheet");c.setAttribute("type","text/css");c.setAttribute("href",b+"xcode5.css");c.setAttribute("id","xcode5");a.appendChild(c)}}};
document.addEventListener("DOMContentLoaded",function(){-1<navigator.userAgent.indexOf("Xcode/")?(xcode=new Ja,xcode.e()):xcode=void 0});
